// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import AppointmentCalendarController from "controllers/appointment_calendar_controller"
application.register("appointment-calendar", AppointmentCalendarController)

import CategoryServiceController from "controllers/category_service_controller"
application.register("category-service", CategoryServiceController)

import CopyController from "controllers/copy_controller"
application.register("copy", CopyController)

import DropdownController from "controllers/dropdown_controller"
application.register("dropdown", DropdownController)

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import HeroSearchController from "controllers/hero_search_controller"
application.register("hero-search", HeroSearchController)

import LocationModalController from "controllers/location_modal_controller"
application.register("location-modal", LocationModalController)

import NotificationsController from "controllers/notifications_controller"
application.register("notifications", NotificationsController)

import SearchModalController from "controllers/search_modal_controller"
application.register("search-modal", SearchModalController)
