development:
  cleanup_pending_appointments_job:
    class: CleanupPendingAppointmentsJob
    queue: default
    schedule: every day at 2am
    description: Automatically remove appointments older than present day.

production:
  cleanup_pending_appointments_job:
    class: CleanupPendingAppointmentsJob
    queue: default
    schedule: every day at 2am
    description: Automatically remove appointments older than present day.

staging:
  cleanup_pending_appointments_job:
    class: CleanupPendingAppointmentsJob
    queue: default
    schedule: every day at 2am
    description: Automatically remove appointments older than present day.

